### ISSUE TITLE
IMU data problem

### ISSUE THREAD

**Issue by lanyusea** [AmroShohoud/myo-drone#1]
Hi, that is an amazing work but I have a question about the pitch and yaw axis.

From my understanding, the pitch and yaw depends on your initial position.

for example, when the logo side up and you move hand left, MYO rotates with its raw axis but when the logo side left and you move hand left, MYO rotates with its pitch axis this case.

Could you tell me how to handle this problem? Since I'm not quite familiar with js I cannot find some code related to this. 

Thanks.

**Comment by AmroShohoud** [comment]
Hello,

Have you tried calibrating the armband? Basically you find this in the
settings and it would ask you a series of questions about how you prefer to
wear the armband and then will save this into a personalized account under
your name. I think this would fix the problem.

Thank you for your interest, let me know if it doesn't work!

Best,
Amro

On Fri, Feb 6, 2015 at 1:42 AM, Aqua notifications@github.com wrote:

> Hi, that is an amazing work but I have a question about the pitch and yaw
> axis.
> 
> From my understanding, the pitch and yaw depends on your initial position.
> 
> for example, when the logo side up and you move hand left, MYO rotates
> with its raw axis but when the logo side left and you move hand left, MYO
> rotates with its pitch axis this case.
> 
> Could you tell me how to handle this problem? Since I'm not quite familiar
> with js I cannot find some code related to this.
> 
> Thanks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/AmroShohoud/myo-drone/issues/1.

## 

Amro Shohoud
Shohouda@gmail.com
425-463-9340
Class of 2017 | University of Texas at Austin | B.S. Computer Science
Philanthropy Director | Delta Epsilon Psi Fraternity, Inc.

**Comment by lanyusea** [comment]
Hi,

Thanks for your reply but I'm still not quite clear about how the `calibration` solves this problem.

From my understanding the yaw/pitch/row is related to the logo side of myo, am I right?

And I checked the [myo support page](https://support.getmyo.com/hc/en-us/articles/203829315-Creating-a-custom-calibration-profile-for-your-Myo-armband), the wearing prefer is just about `usb to finger` or `usb to wrist`. I still don't understand how this solved the axis issue I mentioned.

Thanks again.

**Comment by lanyusea** [comment]
Hi Amro,

Thanks for your answer and I found I make a mistake when understanding the rotation.

Thanks again.
